# [vars]
# MY_VARIABLE = "my-value"

# [[durable_objects.bindings]]
# name = "Rooms"
# class_name = "Rooms"

# [[migrations]]
# tag = "v1.1.1"          # Should be unique for each entry
# new_classes = ["Rooms"]
name = "some-lovely-games"
compatibility_date = "2024-07-18"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = "./dist"
