import { createConfig } from "@tokenami/css";

export default createConfig({
	include: ["./src/**/*.{ts,tsx}"],
	grid: "0.25rem",
	responsive: {},
	theme: {
		alpha: {},
		anim: {},
		border: {
			solid: "solid",
		},
		color: {
			"slate-100": "#f1f5f9",
			"slate-700": "#334155",
			primary: "#0ea5e9",
			white: "#f3f4f1",
			black: "#1c202f",
			yellow: "#f4cd2e",
			blue: "#79c1c5",
			peach: "#e49d97",
			orange: "#e18b47",
			green: "#82bc62",
			"purple-0": "#504d72",
			"purple-1": "#7271b2",
		},
		ease: {},
		"font-size": {
			huge: "100px",
		},
		leading: {},
		"line-style": {},
		radii: {},
		size: {
			full: "100%",
			half: "50%",
			screenh: "100vh",
			screenw: "100vw",
		},
		shadow: {},
		surface: {},
		tracking: {},
		transition: {},
		weight: {
			bold: "900",
		},
		z: {},
	},
	aliases: {
		bg: ["background-color"],
		m: ["margin"],
		mx: ["margin-left", "margin-right"],
		my: ["margin-top", "margin-bottom"],
		mt: ["margin-top"],
		mr: ["margin-right"],
		mb: ["margin-bottom"],
		ml: ["margin-left"],
		p: ["padding"],
		px: ["padding-left", "padding-right"],
		py: ["padding-top", "padding-bottom"],
		pt: ["padding-top"],
		pr: ["padding-right"],
		pb: ["padding-bottom"],
		pl: ["padding-left"],
		size: ["width", "height"],
	},
});
